{
 "title": "${title}",
 "description": "${title}",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "График переходных процессов",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Действительное значение момента",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "forceNm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "torque",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 11 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 18 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Действительная частота вращения двигателя",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 20 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 23 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 14, "y": 25 }, "content": "\n\n\n\n" },
  {
   "title": "Действительное значение тока якоря",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "description": "dsfd", "gridPos": { "h": 10, "w": 10, "x": 14, "y": 27 }, "content": "${shortInfo}" }
 ]
}