server.port: 8090

application:
  devices:
    dictionary:
      tcp-siemens-sinamics-g120:
        name: Sinamics G120
        manufacturer: Siemens
        type: Преобразователь частоты
        connection:
          protocol: TCP
          params: ip, rack, slot
        read:
          params: number, index, dataType
        defaultMetrics:
          - name: speed
            description: Действительная частота вращения двигателя
            unit: hertz
            access: 63, 0, FLOAT_32
            jvmType: float
          - name: current
            description: Действительное значение тока якоря
            unit: amp
            access: 68, 0, FLOAT_32
            jvmType: float
          - name: torque
            description: Действительное значение момента
            unit: forceNm
            access: 80, 0, FLOAT_32
            jvmType: float
          - name: temperature
            description: Температура
            unit: celsius
            access: 35, 0, FLOAT_32
            jvmType: float
      tcp-siemens-sinamics-g120-emulator:
        name: Sinamics G120 Emulator
        manufacturer: Vladimir Kostin
        type: Преобразователь частоты. Эмуляция на Spring Boot
        connection:
          protocol: HTTP
          params: ip, port, rack, slot
        read:
          params: number, index, dataType
        defaultMetrics:
          - name: speed
            description: Действительная частота вращения двигателя
            unit: hertz
            access: 63, 0, FLOAT_32
            jvmType: float
          - name: current
            description: Действительное значение тока якоря
            unit: amp
            access: 68, 0, FLOAT_32
            jvmType: float
          - name: torque
            description: Действительное значение момента
            unit: forceNm
            access: 80, 0, FLOAT_32
            jvmType: float
          - name: temperature
            description: Температура
            unit: celsius
            access: 35, 0, FLOAT_32
            jvmType: float

spring:
  data:
    #mongoDB
    mongodb:
      authentication-database: admin
      database: WTiAT_MainService
      host: 127.0.0.1
      port: 27017
  #      username: springboot
  #      password: spring
  #jackson
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
